services:
  server:
    build: .
    container_name: pts_board
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        # i2pd:
        # condition: service_started
    ports:
      - "${PORT}:${PORT}"
    environment:
      - LISTEN=${LISTEN}
      - PORT=${PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - RUST_LOG=${RUST_LOG}
  db:
    image: postgres:17.7-alpine3.22
    container_name: pts_board_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
